### ISSUE TITLE
Google license 

### ISSUE THREAD

**Issue by mani144** [godotengine/godot-google-play-billing#23]
Greetings

I have been trying to develop a game and use iap

However there was a problem with the licenses 
I could not find anywhere to place Google license into Godot project. 
I uploaded my game into Google play and I tried to use this plugin without Google license but I could not use it

Please help

**Comment by mani144** [comment]
@m4gr3d please respond

**Comment by Calinou** [comment]
@mani144 Godot contributors are helping people on their spare time. Please be mindful of this :slightly_smiling_face:

**Comment by mani144** [comment]
@Calinou I know, 
and im supporting Godot engine from 2.0 
however the problem took 2 weeks of searching and I did not find any resources, and I don't think i`m the only one who is asking for this>

I even open a reddit topic and said in that topic that if someone knows he should let me know so I can update the docs.

i already contributed to godot docs

**Comment by akien-mga** [comment]
I don't understand what the actual problem is, you should share more information. Are you following the tutorial mentioned in the README, and what does your code look like? What is the actual problem you're talking about?

**Comment by mani144** [comment]
@akien-mga 
sorry for saying like this, but this problem is making me going into loops for exactly two weeks, and I have been doing a lot of searches but could not find anything related to this.

So let me explain it:
I used to develop apps on a different platform and I noticed something quite weird.
Usually, when creating a IAP google gives a License to verify the purchases and also to allow testing purchases.
However, I did not c anything talking about this in Godot so I thought maybe Godot implement IAP differently and I opened a thread in reddit explaining the problem and someone said you can put the licenses ( this was a confirmation that godot uses the same method)

However, nothing in Godot docs or demo is talking about linking godot with google play ( or the license), the only thing mention google play is that you must upload the apk to google ( I have uploaded the apk and iap did not work)

I feel that something missing either in the docs or in the plugin ... 
I tried every possible way and even let my friend reads the docs just in case I missed something or I did not understand it.

please advise and thank you for your time

**Comment by volzhs** [comment]
what "License" are you talking about? is that "License Test" on google developer console?

what do you mean "iap did not work"?
did nothing come up when trying to purchase?
is there any error message?

did you add your test account for a tester at Publish > Test > Internal (or alpha/beta) and accept testing on your account?

**Comment by mani144** [comment]
what "License" are you talking about? is that "License Test" on google developer console?
![image](https://user-images.githubusercontent.com/17520497/108884298-7984be00-7617-11eb-95ca-29e271b95a6c.png)
when you upload an apk, there is an option called Monetization setup 
which provide a license to prevent the unauthorized distribution of your app and test in-app billing integrations 

what do you mean "iap did not work"?
did nothing come up when trying to purchase?
is there any error message?
IAP does not connect using :
payment.startConnection()
no error is shown even in adb logcat


did you add your test account for a tester at Publish > Test > Internal (or alpha/beta) and accept testing on your account?
yes I already installed the game using play store direct USB installation

**Comment by volzhs** [comment]
I didn't set the public key for licensing with my current project, but testing iap works as expected for me.
there probably be something wrong in another place.

**Comment by mani144** [comment]
> 
> 
> I didn't set the public key for licensing with my current project, but testing iap works as expected for me.
> there probably be something wrong in another place.

so you just did the tutorial and added uploaded the apk to google play and did work ?
ok, so you using the debug key as the release key for ur game ?
another question is how did use product ID (SKU) ?
did you add com.android.vending.BILLING as a permission ?

**Comment by volzhs** [comment]
> so you just did the tutorial and added uploaded the apk to google play and did work ?

yes

> also, did you use the debug key as the release key for ur game ?

using release key as debug key

> another question is how did use product ID (SKU) ?

reversed domain form. like `org.godot.product_1`

> did you add com.android.vending.BILLING as a permission ?

no. it's already inside `GodotGooglePlayBilling.1.0.1.release.aar`

**Comment by mani144** [comment]
@volzhs 
so my problem is with startConnection...
I will try and debug and get back to you

**Comment by mani144** [comment]
Sorry for the trouble guys
It seems, I was using an android emulator which does not have iap ( the default emulator as far as read)
However using something like bluestack, it's a necessity that you must sign in to Google play to make it work. 
If used my personal phone this wasn't going to be a problem

I will try to update the docs in a way that explains it
 Thabk you all for your trouble
