### ISSUE TITLE
Updating plugin to PBL v4

### ISSUE THREAD

**Issue by natetrost** [godotengine/godot-google-play-billing#26]
1.0.1 uses the older version 3.0 of Play Billing Library plugin. The current version is 4.0.

A PR to update the plugin to 4.0, incorporating API changes and adding some missing feature coverage is here:
https://github.com/godotengine/godot-google-play-billing/pull/25

A PR to update the tutorial documentation of the plugin for v1.1 is here:
https://github.com/godotengine/godot-docs/pull/5367

A PR to update the Android IAP demo for v1.1 of the plugin is here:
https://github.com/godotengine/godot-demo-projects/pull/659

**Comment by natetrost** [comment]
Bumping this to note a new [PR #29](https://github.com/godotengine/godot-google-play-billing/pull/29) with a minor feature addition and that the Releases needs an update to 1.1.1 so I can get the docs and sample PRs submitted.

**Comment by slabgames** [comment]
``` java.lang.RuntimeException: Unable to resume activity {com.mycompany.cpr/com.godot.game.GodotApp}: java.lang.IllegalArgumentException: Signal billing_resume is not registered for this plugin.
```
I'm getting this error when running on device. Anyone getting this issue as well?

**Comment by SnailRabbids** [comment]
@natetrost
Hi, still in progress?
After 2 months, PBL v3 will no longer be supported.

**Comment by SnailRabbids** [comment]
@natetrost  Mb we could tag (@) someone and ask to create new release?

**Comment by timoschwarzer** [comment]
Please see https://github.com/godotengine/godot-google-play-billing/issues/35
