### ISSUE TITLE
Billing Library version 3

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot-google-play-billing#34]
Tried uploading to play console and getting this error:

Error
We've detected this app uses an unsupported version of Play billing. Please upgrade to Billing Library version 3 or newer to publish this app. [Learn More about Billing Library 3.](https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html)

using v.1.0.1

**Comment by HEAVYPOLY** [comment]
Yes, had to build the plugin using latest and it worked.

**Comment by joshua-Ig** [comment]
@HEAVYPOLY I got it to work now too, but I now have the issue with the Singleton 
if Engine.has_singleton("GodotGooglePlayBilling"): returns false

**Comment by HEAVYPOLY** [comment]
Engine.has_singleton("GodotGooglePlayBilling") returns true for me.
 I did have to change the code a bit following the updated docs for godot google play billing though, there's some new callback functions

**Comment by timoschwarzer** [comment]
See https://github.com/godotengine/godot-google-play-billing/issues/35
