### ISSUE TITLE
All new apps must use Billing Library version 4 or newer. By November 1, 2022

### ISSUE THREAD

**Issue by QuangDung-Wenal** [godotengine/godot-google-play-billing#37]
According to #35, the latest code already uses V4, so do I need to update to a newer version or stay the same?
I have more than 50 games currently on the google store, if I have to upgrade all of them, it will be quite tiring :)

**Comment by timoschwarzer** [comment]
tl;dr: yes, you need to update. See my last comment in that issue you mentioned.

**Comment by chazzledazzle10** [comment]
hey guys im trying to integrate google pay into my game and it throws out an error in the command line debugger saying its below 3 when i set it to 4 in the gradle file???
