### ISSUE TITLE
getting error purchasing item // closed

### ISSUE THREAD

**Issue by chazzledazzle10** [godotengine/godot-google-play-billing#40]
hey guys please help me out ive been stuck for so long i dont know what to do. so this is my code for the purchase button down
![image](https://user-images.githubusercontent.com/44733876/204328613-37285a69-5d4c-4e57-88ca-cc8ab83d62a5.png)

and this is the result from the command line debugger when im using my phone 
![image](https://user-images.githubusercontent.com/44733876/204328881-faddbbfc-955f-4c7c-95b4-6c6277f9355f.png)

so i think its not connecting to the android/google api and the response.status code is 1 which i have been trying to figure out what it means? 

please someone help

**Comment by chazzledazzle10** [comment]
i will also add that in the connected function i have tried queryskudetails and query product details and they both make no differenced what so ever.

**Comment by chazzledazzle10** [comment]
Hey thank you for the advise but I sorted this out. Im currently logged out of Github and cant comment. Sent from Mail for Windows From: NianoTTSent: 18 May 2023 16:33To: godotengine/godot-google-play-billingCc: chazzledazzle10; AuthorSubject: Re: [godotengine/godot-google-play-billing] getting error purchasing item (Issue #40) Some stuff I noticed:are you using 2.0-rc1 of this plugin? the older ones won't workdo you have all the signals connected?in _on_connected, you call your own signal function?instead, you need to call querySkuDetails() with the same parameters, and remove queryPurchases, it doesn't exist in 2.0calling it before purchase is requiredall of this expects the IAP set up correctly with Google in the dev console and you need (!) to at least once upload a build to it (Testing Track is fine) and run the purchase from it (so, install it from Google and run), so it acknowledges that this iap is active. Just running it locally will not work, at least once you must run in from Google.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by chazzledazzle10** [comment]
Hi mate, thank you for getting back. I will mark it as soved soon, just out with the family at the moment. Thanks. Sent from Mail for Windows From: NianoTTSent: 19 May 2023 12:50To: godotengine/godot-google-play-billingCc: chazzledazzle10; AuthorSubject: Re: [godotengine/godot-google-play-billing] getting error purchasing item (Issue #40) Hey thank you for the advise but I sorted this out.👍If you got it working you can close the issue as it's not a bug in the plugin then.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by chazzledazzle10** [comment]
> > Hey thank you for the advise but I sorted this out.
> 
> 👍
> 
> If you got it working you can close the issue as it's not a bug in the plugin then.

Hi mate ive just logged back in. i cant see a way to close the thread?

**Comment by NianoTT** [comment]
> > > Hey thank you for the advise but I sorted this out.
> > 
> > 
> > 👍
> > If you got it working you can close the issue as it's not a bug in the plugin then.
> 
> Hi mate ive just logged back in. i cant see a way to close the thread?

On Desktop, at the very bottom right next to "Comment" is a "Close Issue" button.
