### ISSUE TITLE
Singleton does not exist

### ISSUE THREAD

**Issue by bobokox** [godotengine/godot-google-play-billing#54]
Hi!

I've tried to setup the plugin in 4.0.3 using [finepointcgi](https://github.com/finepointcgi)'s release. I can see the plugin in the android export settings and i checked it, but the singleton is not there. 

`var payment = Engine.get_singleton("GodotGooglePlayBilling")`
-> Failed to retrieve non-existent singleton 'GodotGooglePlayBilling'.

`print(Engine.get_singleton_list())`
-> GodotGooglePlayBilling is not in the list

Am I doing something wrong?

Thank you!

**Comment by NianoTT** [comment]
Just to make sure, you are trying it on Android?
The singleton won't be there if you run it on desktop.

**Comment by bobokox** [comment]
Thank you for the quick reply. Yes, remote debug on android. No singleton in the list.

**Comment by bobokox** [comment]
my bad. I've restarted the engine and the plugin was somehow unchecked again.
It's there now!
