### ISSUE TITLE
Crash after calling an invalid SKU as the argument

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot-google-play-billing#9]
"android.test.canceled" is supposed to simulate a canceled purchase, I can use "android.test.purchased" to test purchases just fine, maybe "android.test.canceled" only works with the old billing API but It would be nice if the game didn't crash or at least an error message was printed to make the reason why the game crashed more clear.

**Comment by MightyPrinny** [comment]
This looks very similar https://github.com/dooboolab/react-native-iap/issues/386

**Comment by MightyPrinny** [comment]
"android.test.canceled" works, the crash was my fault, but I'll keep this open because there aren't any error messages when you call purchase with an SKU that doesn't exist or if you call it before querySkuDetails succeeds.

**Comment by timoschwarzer** [comment]
@MightyPrinny The error is broken in the current release. It's already fixed on `master` through. I'll make a new release soon.
